language: cpp

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install:
  - git submodule update --init --recursive
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=$PATH:`pwd`/depot_tools
  - gclient sync

matrix:
  include:
    - compiler: gcc
      os: linux
      env: GN_ARGS='gcc_cc="gcc-4.9" gcc_cxx="g++-4.9" is_clang=false'

    - compiler: gcc
      os: linux
      env: GN_ARGS='gcc_cc="gcc-4.9" gcc_cxx="g++-4.9" is_clang=false is_debug=false'

    - compiler: gcc
      os: linux
      env: GN_ARGS='gcc_cc="gcc-4.9" gcc_cxx="g++-4.9" is_clang=false is_official_build=true'

    - compiler: clang
      os: linux
      env: GN_ARGS='is_clang=true'

    - compiler: clang
      os: linux
      env: GN_ARGS='is_clang=true is_debug=false'

    - compiler: clang
      os: linux
      env: GN_ARGS='is_clang=true is_official_build=true'

    - compiler: clang
      os: osx
      env: GN_ARGS='is_clang=true is_official_build=true'

script:
  - gn gen out --args="$GN_ARGS"
  - ninja -C out
  - cd out && ./hello
