name: actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          .cipd/
          buildtools/
          third_party/googletest/src
          third_party/mini_chromium/src
        key: ${{ runner.os }}-DEPS-${{ hashFiles('DEPS') }}
        restore-keys: |
          ${{ runner.os }}-DEPS-

    - name: Set up PATH
      run: |
        echo "`pwd`/depot_tools" >> $GITHUB_PATH

    - name: Sync
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        gclient sync

    - name: Build and run tests
      run: |
        gn gen out
        ninja -C out hello
        ./out/hello
        ninja -C out hello_unittest
        ./out/hello_unittest

